"""Assemble the NASA reproduction summary from results/l1_results.jsonl:
per-configuration 10-fold CV mean (SD), final held-out mean over seeds, and the
thesis-era reference numbers for comparison. Markdown to stdout; LaTeX rows to
results/l1_table.tex. Run any time; reports whatever is complete.
"""
import json
import os
import statistics as st
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
THESIS = {  # thesis-era NASA Aircraft macro-F1, verbatim from main.tex tab:nasa
    ("glove50", "bilstm"): 0.867, ("glove100", "bilstm"): 0.874,
    ("glove200", "bilstm"): 0.874, ("glove300", "bilstm"): 0.873,
    ("avi2vec", "bilstm"): 0.878,
    ("glove50", "bigru"): 0.874, ("glove100", "bigru"): 0.879,
    ("glove200", "bigru"): 0.880, ("glove300", "bigru"): 0.880,
    ("avi2vec", "bigru"): 0.878,
}

RES = os.environ.get("L1_RES", os.path.join(HERE, "results"))
cv = defaultdict(list)
fin = defaultdict(list)
for line in open(os.path.join(RES, "l1_results.jsonl")):
    r = json.loads(line)
    if r["key"].startswith("smoke_"):
        continue
    if r["mode"] == "cv":
        cv[(r["emb"], r["arch"])].append(r["macro_f1"])
    else:
        fin[(r["emb"], r["arch"])].append(r["test_macro_f1"])

order_emb = ["glove50", "glove100", "glove200", "glove300", "avi2vec", "fasttext", "w2vasrs"]
order_arch = ["bilstm", "bigru", "cnn", "meanmlp"]
rows = []
for arch in order_arch:
    for emb in order_emb:
        k = (emb, arch)
        if k not in cv and k not in fin:
            continue
        c = cv.get(k, [])
        f = fin.get(k, [])
        rows.append({
            "emb": emb, "arch": arch,
            "cv_n": len(c),
            "cv_mean": round(st.mean(c), 4) if c else None,
            "cv_sd": round(st.stdev(c), 4) if len(c) > 1 else None,
            "holdout_mean": round(st.mean(f), 4) if f else None,
            "holdout_seeds": len(f),
            "thesis": THESIS.get(k),
        })

hdr = f"{'emb':<10}{'arch':<9}{'CV mean (SD)':<18}{'held-out':<10}{'thesis':<8}"
print(hdr)
for r in rows:
    cvs = f"{r['cv_mean']} ({r['cv_sd']})" if r["cv_mean"] is not None else f"{r['cv_n']}/10 folds"
    print(f"{r['emb']:<10}{r['arch']:<9}{cvs:<18}{str(r['holdout_mean'] or '-'):<10}{str(r['thesis'] or '-'):<8}")

with open(os.path.join(RES, "l1_table.tex"), "w") as f:
    f.write("% Generated by l1_report.py -- NASA Aircraft reproduction\n")
    for r in rows:
        if r["cv_mean"] is None or r["cv_sd"] is None:
            continue
        f.write(f"{r['arch']} & {r['emb']} & {r['cv_mean']:.3f} ({r['cv_sd']:.3f}) & "
                f"{r['holdout_mean'] if r['holdout_mean'] else '--'} & "
                f"{r['thesis'] if r['thesis'] else '--'} \\\\\n")
print("\nwrote results/l1_table.tex")
