"""Summarises asrs_results.jsonl per configuration.

For each embedding and architecture it prints the 10-fold CV mean and SD,
the held-out mean over the final seeds, and the macro-F1 the initial study
reported for the same configuration. Smoke-test rows are skipped. Prints a
text table and writes LaTeX rows to asrs_table.tex, both under ASRS_RES.
Can be run at any point; it reports whatever has finished.
Run: python3 report.py
"""
import json
import os
import statistics
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
INITIAL_STUDY = {
    ("glove50", "bilstm"): 0.867, ("glove100", "bilstm"): 0.874,
    ("glove200", "bilstm"): 0.874, ("glove300", "bilstm"): 0.873,
    ("avi2vec", "bilstm"): 0.878,
    ("glove50", "bigru"): 0.874, ("glove100", "bigru"): 0.879,
    ("glove200", "bigru"): 0.880, ("glove300", "bigru"): 0.880,
    ("avi2vec", "bigru"): 0.878,
}

RES = os.environ.get("ASRS_RES", os.path.join(HERE, "results"))
cv_scores = defaultdict(list)
final_scores = defaultdict(list)
for line in open(os.path.join(RES, "asrs_results.jsonl")):
    result = json.loads(line)
    if result["key"].startswith("smoke_"):
        continue
    if result["mode"] == "cv":
        cv_scores[(result["emb"], result["arch"])].append(result["macro_f1"])
    else:
        final_scores[(result["emb"], result["arch"])].append(result["test_macro_f1"])

order_emb = ["glove50", "glove100", "glove200", "glove300", "avi2vec", "fasttext", "w2vasrs"]
order_arch = ["bilstm", "bigru", "cnn", "meanmlp"]
rows = []
for arch in order_arch:
    for emb in order_emb:
        config = (emb, arch)
        if config not in cv_scores and config not in final_scores:
            continue
        cv = cv_scores.get(config, [])
        final = final_scores.get(config, [])
        rows.append({
            "emb": emb, "arch": arch,
            "cv_n": len(cv),
            "cv_mean": round(statistics.mean(cv), 4) if cv else None,
            "cv_sd": round(statistics.stdev(cv), 4) if len(cv) > 1 else None,
            "holdout_mean": round(statistics.mean(final), 4) if final else None,
            "holdout_seeds": len(final),
            "thesis": INITIAL_STUDY.get(config),
        })

header = f"{'emb':<10}{'arch':<9}{'CV mean (SD)':<18}{'held-out':<10}{'initial':<8}"
print(header)
for row in rows:
    if row["cv_mean"] is not None:
        cv_text = f"{row['cv_mean']} ({row['cv_sd']})"
    else:
        cv_text = f"{row['cv_n']}/10 folds"
    print(f"{row['emb']:<10}{row['arch']:<9}{cv_text:<18}{str(row['holdout_mean'] or '-'):<10}{str(row['thesis'] or '-'):<8}")

with open(os.path.join(RES, "asrs_table.tex"), "w") as f:
    f.write("% Generated by report.py -- NASA Aircraft reproduction\n")
    for row in rows:
        if row["cv_mean"] is None or row["cv_sd"] is None:
            continue
        f.write(f"{row['arch']} & {row['emb']} & {row['cv_mean']:.3f} ({row['cv_sd']:.3f}) & "
                f"{row['holdout_mean'] if row['holdout_mean'] else '--'} & "
                f"{row['thesis'] if row['thesis'] else '--'} \\\\\n")
print("\nwrote results/asrs_table.tex")
